# Generated by Django 5.1.3 on 2024-12-03 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('bioma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Queimada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('satelite', models.CharField(max_length=100)),
                ('dia_sem_chuva', models.IntegerField()),
                ('precipitacao', models.FloatField()),
                ('risco_fogo', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('frp', models.FloatField()),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estatisticas.municipio')),
            ],
        ),
    ]
