# Generated by Django 5.1.3 on 2024-12-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queimada',
            name='pais',
            field=models.CharField(default='Brasil', max_length=50),
        ),
    ]
