# Generated by Django 5.1.3 on 2024-12-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas', '0002_queimada_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queimada',
            name='dia_sem_chuva',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
