# Generated by Django 5.1.3 on 2024-12-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas', '0003_alter_queimada_dia_sem_chuva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='bioma',
        ),
        migrations.RemoveField(
            model_name='queimada',
            name='data_hora',
        ),
        migrations.RemoveField(
            model_name='queimada',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='queimada',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='queimada',
            name='precipitacao',
        ),
        migrations.RemoveField(
            model_name='queimada',
            name='satelite',
        ),
    ]
