# Generated by Django 5.1.3 on 2024-12-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas', '0004_remove_municipio_bioma_remove_queimada_data_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queimada',
            name='frp',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='queimada',
            name='risco_fogo',
            field=models.FloatField(default='0.0'),
        ),
    ]
