# Generated by Django 5.1.3 on 2024-12-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas', '0007_alter_queimada_risco_fogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queimada',
            name='dia_sem_chuva',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='queimada',
            name='frp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='queimada',
            name='risco_fogo',
            field=models.FloatField(default=0.0),
        ),
    ]
