# Generated by Django 5.1.3 on 2024-12-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estatisticas', '0011_alter_queimada_frp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queimada',
            name='dia_sem_chuva',
        ),
        migrations.RemoveField(
            model_name='queimada',
            name='pais',
        ),
        migrations.AlterField(
            model_name='municipio',
            name='estado',
            field=models.CharField(default='AAAA', max_length=100),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='nome',
            field=models.CharField(default='AAAA', max_length=200),
        ),
    ]
